Models/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebTest1.Models
{
    public class EmployeeController : Controller
    {
        private databaseEntities1 db = new databaseEntities1();

        // GET: /Employee/
        public ActionResult Index(string type = "empty")
        {
            if (!MySession.Current.CanOpenList)
                return RedirectToAction("Error", "Home");

            if (type == "edit")
            {
                ViewBag.message = @"
                <script type=""text/javascript"">
                    $(document).ready(function () {
                        $.growl({ title: ""Поздравляем!"", message: ""Запись была отредактирована"" });
                    });
                </script>";
            }

            if (type == "delete")
            {
                ViewBag.message = @"
                <script type=""text/javascript"">
                    $(document).ready(function () {
                        $.growl({ title: ""Сожалеем!"", message: ""Запись была удалена"" });
                    });
                </script>";
            }

            if (type == "create")
            {
                ViewBag.message = @"
                <script type=""text/javascript"">
                    $(document).ready(function () {
                        $.growl({ title: ""Поздравляем!"", message: ""Запись была добавлена"" });
                    });
                </script>";
            }

            var employee = db.employee.Include(e => e.department);
            return View(employee.ToList());
        }

        // GET: /Employee/Details/5
        public ActionResult Details(long? id)
        {
            if (!MySession.Current.CanUseSearch)
                return RedirectToAction("Error", "Home");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee employee = db.employee.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: /Employee/Create
        public ActionResult Create()
        {
            if (!MySession.Current.CanCRUD)
                return RedirectToAction("Error", "Home");

            ViewBag.employee_ref_department = new SelectList(db.department, "department_id", "department_title");
            return View();
        }

        // POST: /Employee/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "employee_id,employee_firstname,employee_name,employee_lastname,employee_birthday,employee_ref_department,employee_datestart,employee_money")] employee employee, HttpPostedFileBase file)
        {
            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {
                byte[] picture = new byte[file.ContentLength];
                file.InputStream.Read(picture, 0, file.ContentLength);
                employee.employee_photo = picture;
            }

            if (ModelState.IsValid)
            {
                db.employee.Add(employee);
                db.SaveChanges();

                return RedirectToAction("Index", new { type = "create" });
            }

            ViewBag.employee_ref_department = new SelectList(db.department, "department_id", "department_title", employee.employee_ref_department);


            return View(employee);
        }

        // GET: /Employee/Edit/5
        public ActionResult Edit(long? id)
        {
            if (!MySession.Current.CanCRUD)
                return RedirectToAction("Error", "Home");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee employee = db.employee.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.employee_ref_department = new SelectList(db.department, "department_id", "department_title", employee.employee_ref_department);
            return View(employee);
        }

        // POST: /Employee/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "employee_id,employee_firstname,employee_name,employee_lastname,employee_birthday,employee_ref_department,employee_datestart,employee_money,employee_photo")] employee employee,
            HttpPostedFileBase file, string remove)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;

                if (remove == "remove")
                {
                    employee.employee_photo = null;
                }
                else
                    if (file != null && file.ContentLength > 0)
                    {
                        byte[] picture = new byte[file.ContentLength];
                        file.InputStream.Read(picture, 0, file.ContentLength);
                        employee.employee_photo = picture;
                    }
                    else
                    {
                        employee.employee_photo = db.employee.Where(p => p.employee_id == employee.employee_id).FirstOrDefault().employee_photo;
                        db.Entry(employee).Property(t => t.employee_photo).IsModified = false;
                    }

                
                db.SaveChanges();
                return RedirectToAction("Index", new { type = "edit"});

            }
            ViewBag.employee_ref_department = new SelectList(db.department, "department_id", "department_title", employee.employee_ref_department);
            return View(employee);
        }

        // GET: /Employee/Delete/5
        public ActionResult Delete(long? id)
        {
            if (!MySession.Current.CanCRUD)
                return RedirectToAction("Error", "Home");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee employee = db.employee.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: /Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            employee employee = db.employee.Find(id);
            db.employee.Remove(employee);
            db.SaveChanges();

            return RedirectToAction("Index", new { type = "delete" });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTest1.Models;

namespace WebTest1.Controllers
{
    public class SearchController : Controller
    {
        private databaseEntities1 db = new databaseEntities1();

        //
        // GET: /AjaxTest/
        [HttpGet]
        public ActionResult Index()
        {
            if (!MySession.Current.CanUseSearch)
            {
                return RedirectToAction("Error", "Home");
            }
            return View();
        }

        /// <summary>
        /// Searching employers without filters
        /// </summary>
        /// <param name="input">Input string</param>
        /// <returns>Employers</returns>
        [HttpPost, ActionName("SimpleSearch")]
        public PartialViewResult Index(string input)
        {
            var found = db.employee.Where(p => (p.employee_firstname + p.employee_name + p.employee_lastname).Contains(input)).Take(10).ToList();
            return PartialView("Search", found);
        }

        [HttpPost, ActionName("Filters")]
        public PartialViewResult Index(string input, string min_s, string max_s, string min_d, string max_d)
        {
            DateTime t;
            DateTime tt;

            var q = int.Parse(min_s);
            var qq = int.Parse(max_s);

            if ((!DateTime.TryParseExact(min_d, "M/d/yyyy", new CultureInfo("en-US"), DateTimeStyles.None, out t)) ||
                (!DateTime.TryParseExact(max_d, "M/d/yyyy", new CultureInfo("en-US"), DateTimeStyles.None, out tt)))
            {
                var found = db.employee.Where(p => (p.employee_firstname + p.employee_name + p.employee_lastname).Contains(input)).
                    Where(p => p.employee_money >= q && p.employee_money <= qq).Take(10).ToList();
                return PartialView("Search", found);
            }
            else
            {
                

                var found = db.employee.Where(p => (p.employee_firstname + p.employee_name + p.employee_lastname).Contains(input)).
                   Where(p => p.employee_money >= q && p.employee_money <= qq).
                    Where(p => p.employee_birthday.Month * 100 + p.employee_birthday.Day > t.Month * 100 + t.Day).
                    Where(p => p.employee_birthday.Month * 100 + p.employee_birthday.Day < tt.Month * 100 + tt.Day).
                        Take(10).ToList();
                return PartialView("Search", found);
            }
        }
    }
}

Views/Search/Index.cshtml
<div class="jumbotron">

    <script src="../Scripts/moment-with-locales.js"></script>
    <script src="../Scripts/bootstrap-datepicker.js"></script>

    <h1>Поиск сотрудников</h1>

    <p>Введите фамилию, имя или отчество сотрудника. Максимально отображется 10 результатов поиска</p>

    <input id="txt_MyTextBox" type="text" name="txt_MyTextBox" value="" class="input_rewrite">

    <script type="text/javascript">
        $(document).ready(function () {

            var serviceURL = '/Search/SimpleSearch';

            $('input#txt_MyTextBox').keyup(function () {

                var nameVar = document.getElementById('txt_MyTextBox').value;

                $.ajax({
                    type: "POST",
                    //url: '<%= Url.Action("SimpleSearch", "Search") %>',
                    url: serviceURL,
                    data: { 'input': nameVar },
                    dataType: "html",
                    success: function (data) {
                        $('#test').html(data);
                    },
                    error: function (xhr, status, error) {
                        alert(xhr.responseText);
                    }
                });
            });
        });
    </script>

    <h1>Результаты поиска</h1>
    <div id="test">Ещё ничего не найдено</div>

    <h1 id="additional_text" style="cursor:pointer">Применить фильтры к поиску &raquo;</h1>

    <script type="text/javascript">

        $(document).ready(function () {
            $('#additional_panel').hide();
            $('#additional_text').click(function (e) {
                e.preventDefault();
                $('#additional_panel').slideDown();
            });
        });

    </script>

    <div id="additional_panel">

        <hr />
        <p>Поиск сотрудников, день рождения которых будет в выбранном диапазоне дат</p>

        <div class="hero-unit">
            <div class="input-daterange" id="datepicker">
                <input type="text" class="input-small input_rewrite date_rewrite" name="start" />
                <span style="vertical-align: top;height:20px"> по </span>
                <input type="text" class="input-small input_rewrite date_rewrite" name="end" />
            </div>
        </div>

        <script type="text/javascript">
            // When the document is ready
            $(document).ready(function () {

                $('.input-daterange').datepicker({
                    todayBtn: "linked",
                    clearBtn: "Clear",
                    locale: "ru"
                });

                $('.input-daterange').datepicker().on('changeDate', function (ev) {
                    var serviceURL = '/Search/Filters';
                    var nameVar = document.getElementById('txt_MyTextBox').value;
                    $.ajax({
                        type: "POST",
                        url: serviceURL,
                        data: {
                            'input': nameVar,
                            'min_s': $("#slider-range").slider("values", 0),
                            'max_s': $("#slider-range").slider("values", 1),
                            'min_d': $('input[name=start]').val(),
                            'max_d': $('input[name=end]').val(),
                        },
                        dataType: "html",
                        success: function (data) {
                            $('#test').html(data);
                        },
                        error: function (xhr, status, error) {
                            alert(xhr.responseText);
                        }
                    });
                });

            });
        </script>

        <hr />
        <p>Поиск сотрудников с определенным уровнем зарплаты</p>

        <div class="demo">
            <p>
                <div id="amount"></div>
            </p>
            <div id="slider-range"></div>
        </div>
        <script>
            $(document).ready(function () {
                $("#slider-range").slider({
                    range: true,
                    min: 0,
                    max: 100000,
                    values: [0, 15000],
                    slide: function (event, ui) {
                        $("#amount").text("" + ui.values[0] + " - " + ui.values[1] + " р.");
                        var serviceURL = '/Search/Filters';
                        var nameVar = document.getElementById('txt_MyTextBox').value;
                        $.ajax({
                            type: "POST",
                            url: serviceURL,
                            data: {
                                'input': nameVar,
                                'min_s': $("#slider-range").slider("values", 0),
                                'max_s': $("#slider-range").slider("values", 1),
                                'min_d': $('input[name=start]').val(),
                                'max_d': $('input[name=end]').val(),
                            },
                            dataType: "html",
                            success: function (data) {
                                $('#test').html(data);
                            },
                            error: function (xhr, status, error) {
                                alert(xhr.responseText);
                            }
                        });
                    }
                });
                $("#amount").text("" + $("#slider-range").slider("values", 0) + " - " + $("#slider-range").slider("values", 1) + " р.");
            });
        </script>

       

    </div>

</div>

Views/Search/Search.cshtml
@model IEnumerable<WebTest1.Models.employee>

@if (Model.Count() == 0)
{
    <p>По запросу нет результатов</p>
}
else
{
    <table class="table">
        <tr>
            <td>Фамилия</td>
            <td>Имя</td>
            <td>Отчество</td>
            <td>Дата рождения</td>
            <td>Зарплата</td>
            <td>Фотография</td>
            <td>Название отдела</td>
            <td>Профиль</td>

                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @item.employee_firstname
                </td>
                <td>
                    @item.employee_name
                </td>
                <td>
                    @item.employee_lastname
                </td>
                <td>
                    @item.employee_birthday.ToShortDateString()
                </td>
                <td>
                    @String.Format("{0:0.00}", item.employee_money)
                </td>
                <td>
                    @if ((item.employee_photo != null) && (item.employee_photo.Length != 0))
                    {
                        <img src="@String.Format("data:image/gif;base64,{0}", Convert.ToBase64String(item.employee_photo))" width="32" height="32" />
                    }
                    else
                    {
                        <p>нет</p>
                    }
                </td>
                <td>
                    @item.department.department_title
                </td>
                <td>
                    @Html.ActionLink("Просмотреть", "Details", "Employee", new { id = item.employee_id }, null)
                </td>
            </tr>
                }
            </table>
}